### ISSUE TITLE
Training times, plans for larger open models?

### ISSUE THREAD

**Issue by kno10** [state-spaces/mamba#160]
It would be great if you could report the hardware used for training, and the resulting training time for the different model sizes.
Any plans on training larger models under a permissive license? So far, 7B seems to be a sweet spot for many, and if there were a well pretrained Mamba of this size (along with suitable finetuning examples), many more users might give it a try.
And if the 7B model turns out to be competitive with Mistral-7B, it might receive considerable attention this way.

**Comment by albertfgu** [comment]
The models were trained on A100s. Training times depend on hardware, model size, and token count. One can extrapolate based on costs of a comparable Transformer.

It would great if a 7B mamba was trained :) we're happy to support such efforts!

**Comment by kno10** [comment]
It would be nice if you could document training times/scaling for the 790m/1.4B/2.8B models showcased.
Yes, the values will likely be similar to transformer-based models (LLaMA2 7B was reported with 184320 GPU hours), but implementation issues (e.g., Flash Attention2 vs. the standard approach) do make a difference, and earlier results from scaling transformers may not be that reliable (well, in the end the amount and quality of the training data will certainly be the most important factor anyway).
Does together AI have any plans on further scaling this and/or extending multi-lingual capabilities? For my understanding, they were involved at least in the 2.8-slimpj model, and trained StripedHyena-7B?

**Comment by albertfgu** [comment]
I don't think we are able to get the exact hours because our training runs were often stopped and trained across different clusters / hardware configurations. Why do you need this?

I'm not aware of any plans that Together AI has. Cartesia AI does not have plans to train a larger model at the moment. I am aware of some groups who have reached out with interest in training larger Mamba models, but I'm not sure how they are going. This is speculation, but I think it is reasonably likely that a 7B model will be released within a few months. Hope this helps!
