### ISSUE TITLE
RuntimeError: Expected u.is_cuda() to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

### ISSUE THREAD

**Issue by PVTHust** [state-spaces/mamba#275]
I got error when i use colab withT4-gpu
RuntimeError                              Traceback (most recent call last)
[<ipython-input-52-0e7957facd12>](https://localhost:8080/#) in <cell line: 19>()
     45                                   ) as cam:
     46 
---> 47                               grayscale_cam = cam(input_tensor=input_tensor.transpose(-1,-3),
     48                                                   targets=targets)[0, :]
     49                               cam_image = show_cam_on_image( np.repeat([min_max_preprocess(img)], 3, axis=0).transpose(1,2,0), grayscale_cam, use_rgb=True)

20 frames
[/usr/local/lib/python3.10/dist-packages/mamba_ssm/ops/selective_scan_interface.py](https://localhost:8080/#) in forward(ctx, u, delta, A, B, C, D, z, delta_bias, delta_softplus, return_last_state)
     40             C = rearrange(C, "b dstate l -> b 1 dstate l")
     41             ctx.squeeze_C = True
---> 42         out, x, *rest = selective_scan_cuda.fwd(u, delta, A, B, C, D, z, delta_bias, delta_softplus)
     43         ctx.delta_softplus = delta_softplus
     44         ctx.has_z = z is not None

RuntimeError: Expected u.is_cuda() to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

**Comment by VagoLapis** [comment]
是用torch1.X版本不会报错“Expected u.is_cuda() to be true, but got false.”，但是在导入mamba_ssm时会报错

**Comment by SahilNawale** [comment]
your model is not on cuda. Use model.cuda() and then run

**Comment by lijoe123** [comment]
> your model is not on cuda. Use model.cuda() and then run

Hello, could you please tell me where can i add `model.cuda(`) ?

**Comment by ghost-baigao** [comment]
> 您的模型不在 CUDA 上。使用 model.cuda（），然后运行

那要在那个地方加入model.cuda（）呢。我是用了MiM-ISTD这个架构，但是也出现这个问题了，需要怎么解决呢

**Comment by havinggood** [comment]
> > 您的模型不在 CUDA 上。使用 model.cuda（），然后运行
> 
> 那要在那个地方加入model.cuda（）呢。我是用了MiM-ISTD这个架构，但是也出现这个问题了，需要怎么解决呢

hello, I also have this problem when I try to use MiM_ISTD architecture, please ask if you have solved it

**Comment by ghost-baigao** [comment]
if __name__ == '__main__':
&nbsp; &nbsp; device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
&nbsp; &nbsp; input_ = torch.Tensor(5, 3, 256, 256).to(device)
&nbsp; &nbsp; net = MiM([2]*3,[8, 16, 32, 64, 128]).to(device)
&nbsp; &nbsp; out=net(input_)
这样将模型加载到gpu上，可以解决Expected u.is_cuda() to be true，but got false这个问题。但是加上之后，会出现另一个报错Traceback (most recent call last):   File "/home/LYH/MiM-ISTD/mim_network.py", line 833, in <module&gt;     out=net(input_)   File "/home/LYH/anaconda3/envs/mim/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl     return forward_call(*input, **kwargs)   File "/home/LYH/MiM-ISTD/mim_network.py", line 800, in forward     deconc3 = self.deconv3(t4)   File "/home/LYH/anaconda3/envs/mim/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl     return forward_call(*input, **kwargs)   File "/home/LYH/MiM-ISTD/mim_network.py", line 766, in forward     x = self.expand(x)   File "/home/LYH/anaconda3/envs/mim/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl     return forward_call(*input, **kwargs)   File "/home/LYH/anaconda3/envs/mim/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward     return F.linear(input, self.weight, self.bias) RuntimeError: mat1 and mat2 shapes cannot be multiplied (320x256 and 128x256)
这个报错我目前还没有解决。若你能解决这个报错，望告知解决方法。








&amp;#x265A;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "state-spaces/mamba"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年2月22日(星期六) 下午4:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [state-spaces/mamba] RuntimeError: Expected u.is_cuda() to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.) (Issue #275)



     
您的模型不在 CUDA 上。使用 model.cuda（），然后运行
  
那要在那个地方加入model.cuda（）呢。我是用了MiM-ISTD这个架构，但是也出现这个问题了，需要怎么解决呢
  
hello, I also have this problem when I try to use MiM_ISTD architecture, please ask if you have solved it

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  havinggood left a comment (state-spaces/mamba#275)
   
您的模型不在 CUDA 上。使用 model.cuda（），然后运行
  
那要在那个地方加入model.cuda（）呢。我是用了MiM-ISTD这个架构，但是也出现这个问题了，需要怎么解决呢
  
hello, I also have this problem when I try to use MiM_ISTD architecture, please ask if you have solved it

**Comment by havinggood** [comment]
> if __name__ == '__main__'：
> &nbsp;&nbsp;设备 = torch.device（“cuda” if torch.cuda.is_available（） else “cpu”）
> &nbsp;&nbsp;input_ = 火炬。张量（5， 3， 256， 256）.to（设备）
> &nbsp;&nbsp;net = MiM（[2]*3，[8， 16， 32， 64， 128]）.to（设备）
> &nbsp;&nbsp;out=net（input_）
> 这样将模型加载到gpu上，可以解决Expected u.is_cuda（） to be true，but got false这个问题。但是加上之后，会出现另一个报错Traceback （last last call ）：文件 “/home/LYH/MiM-ISTD/mim_network.py”，第 833 行，在 <module> 中out=net（input_） 文件 “/home/LYH/anaconda3/envs/mim/lib/python3.8/site-packages/torch/nn/modules/module.py”，第 1190 行，_call_impl返回 forward_call（*input， **kwargs） 文件 “/home/LYH/MiM-ISTD/mim_network.py”，第 800 行，在正向 deconc3 = self.deconv3（t4） 文件 “/home/LYH/anaconda3/envs/mim/lib/python3.8/site-packages/torch/nn/modules/module.py”，第 1190 行，_call_impl返回 forward_call（*input， **kwargs） 文件 “/home/LYH/MiM-ISTD/mim_network.py”，第 766 行，正向 x = self.expand（x） 文件 “/home/LYH/anaconda3/envs/mim/lib/python3.8/site-packages/torch/nn/modules/module.py”，第 1190 行，_call_impl返回 forward_call（*input， **kwargs） 文件 “/home/LYH/anaconda3/envs/mim/lib/python3.8/site-packages/torch/nn/modules/linear.py”，第 114 行，正向返回 F.linear（input， self.weight、self.bias）RuntimeError：mat1 和 mat2 形状无法相乘（320x256 和 128x256）
> 这个报错我目前还没有解决。若你能解决这个报错，望告知解决方法。
> 
> &#x265A;
> ***@***.***
> 
> &nbsp;
> […](#)
哈哈，在我将    input_ = torch.Tensor(5, 3, 256, 256)
    net = MiM([2]*3,[8, 16, 32, 64, 128])后面都添加上.to("cuda")后，我也遇到了这个问题，仍未解决，也许我们可以互相添加微信来讨论此模型？

**Comment by ghost-baigao** [comment]
请问，如何加你微信呢？


&amp;#x265A;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "state-spaces/mamba"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年2月22日(星期六) 下午4:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [state-spaces/mamba] RuntimeError: Expected u.is_cuda() to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.) (Issue #275)



    
if name == 'main'：
 &nbsp;&nbsp;设备 = torch.device（“cuda” if torch.cuda.is_available（） else “cpu”）
 &nbsp;&nbsp;input_ = 火炬。张量（5， 3， 256， 256）.to（设备）
 &nbsp;&nbsp;net = MiM（[2]*3，[8， 16， 32， 64， 128]）.to（设备）
 &nbsp;&nbsp;out=net（input_）
 这样将模型加载到gpu上，可以解决Expected u.is_cuda（） to be true，but got false这个问题。但是加上之后，会出现另一个报错Traceback （last last call ）：文件 “/home/LYH/MiM-ISTD/mim_network.py”，第 833 行，在  中out=net（input_） 文件 “/home/LYH/anaconda3/envs/mim/lib/python3.8/site-packages/torch/nn/modules/module.py”，第 1190 行，_call_impl返回 forward_call（*input， **kwargs） 文件 “/home/LYH/MiM-ISTD/mim_network.py”，第 800 行，在正向 deconc3 = self.deconv3（t4） 文件 “/home/LYH/anaconda3/envs/mim/lib/python3.8/site-packages/torch/nn/modules/module.py”，第 1190 行，_call_impl返回 forward_call（*input， **kwargs） 文件 “/home/LYH/MiM-ISTD/mim_network.py”，第 766 行，正向 x = self.expand（x） 文件 “/home/LYH/anaconda3/envs/mim/lib/python3.8/site-packages/torch/nn/modules/module.py”，第 1190 行，_call_impl返回 forward_call（*input， **kwargs） 文件 “/home/LYH/anaconda3/envs/mim/lib/python3.8/site-packages/torch/nn/modules/linear.py”，第 114 行，正向返回 F.linear（input， self.weight、self.bias）RuntimeError：mat1 和 mat2 形状无法相乘（320x256 和 128x256）
 这个报错我目前还没有解决。若你能解决这个报错，望告知解决方法。
 
♚
 @.***
 
&nbsp;
 …
 哈哈，在我将    input_ = torch.Tensor(5, 3, 256, 256)
 net = MiM([2]*3,[8, 16, 32, 64, 128])后面都添加上.to("cuda")后，我也遇到了这个问题，仍未解决，也许我们可以互相添加微信来讨论此模型？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  havinggood left a comment (state-spaces/mamba#275)
  
if name == 'main'：
 &nbsp;&nbsp;设备 = torch.device（“cuda” if torch.cuda.is_available（） else “cpu”）
 &nbsp;&nbsp;input_ = 火炬。张量（5， 3， 256， 256）.to（设备）
 &nbsp;&nbsp;net = MiM（[2]*3，[8， 16， 32， 64， 128]）.to（设备）
 &nbsp;&nbsp;out=net（input_）
 这样将模型加载到gpu上，可以解决Expected u.is_cuda（） to be true，but got false这个问题。但是加上之后，会出现另一个报错Traceback （last last call ）：文件 “/home/LYH/MiM-ISTD/mim_network.py”，第 833 行，在  中out=net（input_） 文件 “/home/LYH/anaconda3/envs/mim/lib/python3.8/site-packages/torch/nn/modules/module.py”，第 1190 行，_call_impl返回 forward_call（*input， **kwargs） 文件 “/home/LYH/MiM-ISTD/mim_network.py”，第 800 行，在正向 deconc3 = self.deconv3（t4） 文件 “/home/LYH/anaconda3/envs/mim/lib/python3.8/site-packages/torch/nn/modules/module.py”，第 1190 行，_call_impl返回 forward_call（*input， **kwargs） 文件 “/home/LYH/MiM-ISTD/mim_network.py”，第 766 行，正向 x = self.expand（x） 文件 “/home/LYH/anaconda3/envs/mim/lib/python3.8/site-packages/torch/nn/modules/module.py”，第 1190 行，_call_impl返回 forward_call（*input， **kwargs） 文件 “/home/LYH/anaconda3/envs/mim/lib/python3.8/site-packages/torch/nn/modules/linear.py”，第 114 行，正向返回 F.linear（input， self.weight、self.bias）RuntimeError：mat1 和 mat2 形状无法相乘（320x256 和 128x256）
 这个报错我目前还没有解决。若你能解决这个报错，望告知解决方法。
 
♚
 @.***
 
&nbsp;
 …
 哈哈，在我将    input_ = torch.Tensor(5, 3, 256, 256)
 net = MiM([2]*3,[8, 16, 32, 64, 128])后面都添加上.to("cuda")后，我也遇到了这个问题，仍未解决，也许我们可以互相添加微信来讨论此模型？

**Comment by havinggood** [comment]
> 请问，如何加你微信呢？
> 
> &#x265A;
> ***@***.***
> 
> &nbsp;
> […](#)

18638637387这是我的微信
