### ISSUE TITLE
Why isn't selective_scan implemented in Triton?

### ISSUE THREAD

**Issue by 0xc1c4da** [state-spaces/mamba#35]
Reading Section D of the paper:
```
1. We read in 𝑂(𝐵𝐿𝐷 + 𝐷𝑁) bytes of memory (∆, A, B, C) from slow HBM to fast SRAM.
2. We discretize to produce A, B of size (𝐵, 𝐿, 𝐷, 𝑁) in SRAM.
3. We perform a parallel associative scan, yielding intermediate states of size (𝐵, 𝐿, 𝐷, 𝑁) in SRAM.
4. We multiply and sum with C, producing outputs of size (𝐵, 𝐿, 𝐷) and write it to HBM
```

I am trying to understand why the `selective_scan` wasn't implemented in Triton? or where the performance benefit comes from implementing this in CUDA C++ for kernel fusion, parallel scan, & recomputation.

I ask because I'm working on my own implementation of the Mamba Mixer in JAX, and wondering if I can get away with implementing the kernels in Pallas

**Comment by tridao** [comment]
Triton does have associative scan, but (1) it only supports scan with 1 float instead of a pair of floats, which is what we need (2) it doesn't have reverse scan yet (needed for the backward pass).
Does Pallas have those?

When Triton has more robust support for scan, it would be simpler to write it in Triton.

**Comment by vmajor** [comment]
Ideally it would be nice to be truly hardware agnostic, in the spirit of the Mamba mission statement. Tying the architecture to CUDA may not be the best way.
