### ISSUE TITLE
Token masking support

### ISSUE THREAD

**Issue by dazzle-me** [state-spaces/mamba#49]
I'm going to train some Mamba variants from scratch on different tasks with both discrete and continuous input, but I'm not sure how the masking mechanism is implemented here (compared to transformer attention masking) 

e.g. we want the model not to take into account some tokens, because depending on the number of padding tokens inference would give different results as I understand.

**Comment by tridao** [comment]
The architecture is new so we're not exactly sure to handle token masking yet.
Since it's a causal model, if you pad on the right, the padding tokens wouldn't affect the output corresponding to other tokens.
E.g. the first 3 outputs of the sequence [a, b, c, pad, pad] would be the same as the 3 outputs of the sequence [a, b, c].

**Comment by dazzle-me** [comment]
I thought the same, thank you!
