### ISSUE TITLE
torch.cuda.amp.custom_fwd(args...) Deprecated

### ISSUE THREAD

**Issue by NLHuang** [state-spaces/mamba#517]
Hi,

The warning is seen when I tried to reproduce the Mamba-2 usage example with pytorch 2.4.0+cu121:

mamba_ssm/ops/selective_scan_interface.py:164: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.

I'm new to github and not sure whether (and how urgently) this needs to be fixed.

**Comment by weilaikeeqi** [comment]
mamba-main/mamba_ssm/ops/selective_scan_interface.py:164: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  def forward(ctx, xz, conv1d_weight, conv1d_bias, x_proj_weight, delta_proj_weight,

I have the same problem.

**Comment by ql0wn4** [comment]
any solution?

**Comment by bibaboulda5** [comment]
i have the same message.
i try to test ComfyUI on local and i have this warning. my graphic card is an old GTX1080TI. Vram is ok at 11Go but cuda are not detected by comfyUI. (comfy updated)
i don't undersand if its because of this problem.
please share info if anyone can help.....i m too noob for this
![cuda probleme](https://github.com/user-attachments/assets/2def424c-6620-42c8-800b-adef54899b7a)
